name: Set Output
description: An action to simplify setting outputs
branding:
  icon: list
  color: white
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.variables }}
inputs:
  variables:
    description: The variables that you want to define, separated by a newline
    required: true
